# Generated by Django 4.1 on 2022-09-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0002_remove_usermodel_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="location",
            new_name="state",
        ),
    ]
