# Generated by Django 4.1.1 on 2022-09-23 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0004_usermodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("CT", "Connecticut"),
                    ("DC", "District of Columbia"),
                    ("MA", "Massachusetts"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="IncomeModel",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.FloatField(default=1.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
