# Generated by Django 4.1.1 on 2022-09-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0006_accountmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NodeModel",
        ),
    ]
