# Generated by Django 4.1.1 on 2022-09-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0008_remove_accountmodel_id_remove_accountmodel_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incomemodel",
            old_name="value",
            new_name="payoutValue",
        ),
    ]
