# Generated by Django 4.1.1 on 2022-09-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0009_rename_value_incomemodel_payoutvalue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incomemodel",
            old_name="payoutValue",
            new_name="value",
        ),
    ]
